[package]
name = "rsepl"
version = "0.1.0"
edition = "2021"

# See more keys and tmainheir definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.146"
tempfile = "3.6.0"
